### ISSUE TITLE
Enhancement: Parameter input for output directory

### ISSUE THREAD

**Issue by dcherry88** [kirkpatrickprice/windows-audit-scripts#3]
The scenario for use I've been engaged on to use this script is to run it against large batches of systems and send back to the output text file to our compliance group for review. It would be helpful if this script had built in -filepath parameter that would allow user's to specify where to save the file on the local system so as to be able to easily pull it from a consistent location across the fleet when retrieving those .txt files. Default path, if not specified, could remain the home directory of the user running the script.

**Comment by flyguy62n** [comment]
Added an OutPath command line option to version 0.4.1
