### ISSUE TITLE
Issue and Enhancement : Get Local Groups and Local Users

### ISSUE THREAD

**Issue by dcherry88** [kirkpatrickprice/windows-audit-scripts#4]
When running this script on systems with fairly large domain directory trees, both the get-wmiobject lines to pull local groups and local users takes an extraordinary amount of time. 

Based off the fact that you are running get-localgroup and get-localuser to output only local information, if you add `-filter "LocalAccount=True"` to your get-wmiobject commands it will render out only the local data and will not spend time pulling domain directory info down. Doing this cut the runtime by half or more in some cases.

As well as this, in order to avoid these commands duplicating the data because of older PowerShell versions, wrapping it in an if conditional will avoid the duplicate data. 

An example of these modifications I put in place to run in our environment:
```
$section="Users_LocalGroups"
  header -text $section
  if($psversiontable.PSVersion.Major -eq 5 -and $psversiontable.PSVersion.Minor -eq 1){
    comment -section $section -text "Powershell version 5.1, running get-localgroup to get local user groups"
    $command={ Get-LocalGroup -ErrorAction silentlycontinue  | Format-Table -AutoSize }

  }else{
    comment -section $section -text "Powershell version less than 5.1, running get-wmiobject to get local user groups"
    $command={ get-wmiobject -class Win32_Group -Filter "LocalAccount=True" | Select-Object Name, LocalAccount, Domain, Description | Format-Table -AutoSize }
  }
    Invoke-MyCommand -section $section -command $command
footer -text $section
```

**Comment by flyguy62n** [comment]
I had removed the offending commands a while back, but I introduced better logic in 0.4.2.  Rather than hard-coded to specific PowerShell versions, I elected to use a test for whether or not the "get-localgroup" and "get-localuser".  If these commands are not present, then it will revert to get-wmiobject.
